In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [3]:
from tensorflow.keras.layers import Input,SimpleRNN,Dense,Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD,Adam

N=number of samples

T=sequence  length

D=number of input features

M=number of hidden units

K=number of output units

In [4]:
N=1
T=10
D=3
K=2
X=np.random.randn(N,T,D)

In [5]:
#make rnn
M=5
i=Input(shape=(T,D))
x=SimpleRNN(M)(i)
x=Dense(K)(x)
model=Model(i,x)

In [6]:
Yhat=model.predict(X)
print(Yhat)

1/1 [==============================] - 2s 2s/step
[[-1.1180539  -0.00318349]]


In [7]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.layers[1].get_weights()

[array([[ 0.82161826, -0.08770114, -0.44722942,  0.36246377,  0.31501776],
        [ 0.52769786, -0.8211737 ,  0.55930144, -0.31528884, -0.5330603 ],
        [-0.05754066,  0.23284358, -0.3711422 ,  0.31597358, -0.26183474]],
       dtype=float32),
 array([[ 0.15587461,  0.28131348, -0.09543263,  0.7634101 , -0.5519635 ],
        [-0.5317682 ,  0.08461885, -0.04235408, -0.4445615 , -0.7145862 ],
        [-0.53730613, -0.02794602,  0.7636928 ,  0.3238009 ,  0.14982466],
        [-0.5299095 , -0.50964564, -0.5658336 ,  0.33866224,  0.15683562],
        [-0.35131726,  0.80819726, -0.2927529 ,  0.00557715,  0.37102294]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [9]:
a,b,c =model.layers[1].get_weights()
print(a.shape,b.shape,c.shape)

(3, 5) (5, 5) (5,)


In [10]:
Wx,Wh,bh =model.layers[1].get_weights()
Wo,bo =model.layers[2].get_weights()