In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity,euclidean_distances
import nltk
from nltk import word_tokenize
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer,PorterStemmer

In [22]:
documents='train tell in the red !!  the yellow !! the green !!'

In [23]:
current_idx=0
word2idx={}
for i in range(0,len(documents)):
    tokens=documents.split(' ')
    for token in tokens:
        if token not in word2idx:
            word2idx[token]=current_idx
            current_idx+=1



In [24]:
word2idx

{'train': 0,
 'tell': 1,
 'in': 2,
 'the': 3,
 'red': 4,
 '!!': 5,
 '': 6,
 'yellow': 7,
 'green': 8}

In [25]:
import requests
url = 'https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv'
r = requests.get(url, allow_redirects=True)

from io import StringIO
data = StringIO(r.text)
df=pd.read_csv(data)

In [26]:
df.head()

text    labels
0  Ad sales boost Time Warner profit\n\nQuarterly...  business
1  Dollar gains on Greenspan speech\n\nThe dollar...  business
2  Yukos unit buyer faces loan claim\n\nThe owner...  business
3  High fuel prices hit BA's profits\n\nBritish A...  business
4  Pernod takeover talk lifts Domecq\n\nShares in...  business

In [27]:
idx=0
word2idx={}
tokenized_docs=[]
for doc in df['text']:
    words=word_tokenize(doc.lower())
    doc_as_int =[]
    for word in words:
        if word not in word2idx:
            word2idx[word]=idx
            idx+=1
        doc_as_int.append(word2idx[word])
    tokenized_docs.append(doc_as_int)

In [28]:
idx2word={v:k for k,v in word2idx.items()}

In [29]:
N=len(df['text'])
N

2225

In [30]:
V=len(word2idx)
V

34762

In [31]:
tf=np.zeros((N,V))

In [32]:
tf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [33]:
for i,doc_as_int in enumerate(tokenized_docs):
    for j in doc_as_int:
        tf[i,j] +=1

In [34]:
document_freq=np.sum(tf>0,axis=0)
idf=np.log(N/document_freq)

In [35]:
N

2225

In [36]:
document_freq

array([ 12, 204, 127, ...,   1,   1,   1])

In [37]:
tf

array([[1., 4., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 1.]])

In [38]:
idf

array([5.22260554, 2.3893922 , 2.86332511, ..., 7.70751219, 7.70751219,
       7.70751219])

In [39]:
tf_idf=tf*idf

In [40]:
np.random.seed(123)

In [41]:
i=np.random.choice(N)
row=df.iloc[i]
print('label:',row['labels'])
print('text:',row['text'].split('\n',1)[0])
print('top 5 items:')

scores=tf_idf[i]
indices=(-scores).argsort()

for j in indices[:5]:
    print(idx2word[j])

label: sport
text: Athens memories soar above lows
top 5 items:
paula
athens
1500m
her
kelly
